include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    unnecessary_breaks: true
    use_key_in_widget_constructors: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
